services:
  - type: web
    name: kafportal-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
    autoDeploy: true
    branch: main
    numInstances: 1
    disk:
      name: kafportal-data
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
